{application,libring,
             [{modules,['Elixir.HashRing','Elixir.HashRing.App',
                        'Elixir.HashRing.Managed','Elixir.HashRing.Utils',
                        'Elixir.HashRing.Worker','Elixir.Inspect.HashRing']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,crypto]},
              {description,"A fast consistent hash ring implementation in Elixir"},
              {registered,[]},
              {vsn,"1.7.0"},
              {mod,{'Elixir.HashRing.App',[]}}]}.
