{application,telemetry_metrics_prometheus_core,
             [{modules,['Elixir.TelemetryMetricsPrometheus.Core',
                        'Elixir.TelemetryMetricsPrometheus.Core.Aggregator',
                        'Elixir.TelemetryMetricsPrometheus.Core.Counter',
                        'Elixir.TelemetryMetricsPrometheus.Core.Distribution',
                        'Elixir.TelemetryMetricsPrometheus.Core.EventHandler',
                        'Elixir.TelemetryMetricsPrometheus.Core.Exporter',
                        'Elixir.TelemetryMetricsPrometheus.Core.LastValue',
                        'Elixir.TelemetryMetricsPrometheus.Core.Registry',
                        'Elixir.TelemetryMetricsPrometheus.Core.Sum']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,telemetry_metrics,
                             telemetry]},
              {description,"Provides a Prometheus format reporter for Telemetry.Metrics definitions.\n"},
              {registered,[]},
              {vsn,"1.2.1"}]}.
